### ISSUE TITLE
getMissions failing

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-platform-common#1]
run `npm test` and see that the getMissions unit spec fails for Nutter Butter

**Comment by cjshawMIT** [comment]
I can’t replicate this? Did you push your latest code to platform-common? I get 4 failures (1 timeout, 1 for delete mission), but nothing to do with getMission for D2L failing? I do get a timeout on   1) authenticateD2LHelper should get instructor banks when given instructor credentials:

Is that the test you mean?
